import Head from 'next/head'
import Link from 'next/link'

import { useCart } from '../hooks/use-cart.js';

import Header from '../components/Header';

import styles from '../styles/Home.module.scss'

export default function Cart() {
  const { cartItems } = useCart();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <div className={styles.container}>

          <h1>Cart</h1>

          <div>
            {cartItems.length > 0 && (
              <ul id="cart-items">
                {cartItems.map(game => {
                  return (
                    <li key={game.id}>
                      <p>{ game.name }</p>
                      <p>${ game.price.toFixed(2) }</p>
                      <p>{ game.quantity }</p>
                    </li>
                  )
                })}
              </ul>
            )}
          </div>

        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  return {
    props: {}
  }
}