import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Home.module.scss'

export default function Game({ game }) {
  console.log('game', game);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <div className={styles.container}>
          <p className={styles.title}>
            <Link href="/">
              <a>
                Video Game Store
              </a>
            </Link>
          </p>
        </div>
      </header>

      <nav className={styles.nav}>
        <div className={styles.container}>
          <ul className={styles.navLinks}>
            <li>
              <a href="#">
                Xbox Series X
              </a>
            </li>
            <li>
              <a href="#">
                Playstation 5
              </a>
            </li>
            <li>
              <a href="#">
                Nintendo Switch
              </a>
            </li>
            <li>
              <a href="#">
                PC
              </a>
            </li>
          </ul>
        </div>
      </nav>

      <main className={styles.main}>
        <div className={`${styles.container} ${styles.productContainer}`}>
          <div className={styles.productImage}>
            <img src={game.image.original_url} alt={`${game.name} Cover`} />
          </div>
          <div className={styles.productDetails}>
            <h1 className={styles.productTitle}>{ game.name }</h1>
            <p className={styles.productDescription}>
              {game.deck}
            </p>
            <p className={styles.productPrice}>
              $60.00
            </p>
            <p className={styles.productBuy}>
              <button className={styles.productBuyButton}>Add to Cart</button>
            </p>
          </div>
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps({ params = {} } = {}) {
  const response = await fetch(`https://www.giantbomb.com/api/game/${params.gameId}/?api_key=${process.env.GIANT_BOMB_API_KEY}&format=json&sort=original_release_date:desc&filter=original_release_date:2016-01-01|2021-05-17&platforms=145,146&field_list=name,image,deck`);
  const { results } = await response.json();
  return {
    props: {
      game: results
    }
  }
}

export async function getStaticPaths() {
  const response = await fetch(`https://www.giantbomb.com/api/games/?api_key=${process.env.GIANT_BOMB_API_KEY}&format=json&sort=original_release_date:desc&filter=original_release_date:2016-01-01|2021-05-17&platforms=145,146&field_list=id`);
  const { results } = await response.json();

  const paths = results.map(({ id }) => {
    return {
      params: {
        gameId: `${id}`,
      },
    };
  });

  return {
    paths,
    fallback: false,
  };
}