import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'

export default function Home({ games }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            Video Game Store
          </h1>
        </div>
      </header>

      <nav className={styles.nav}>
        <div className={styles.container}>
          <ul className={styles.navLinks}>
            <li>
              <a href="#">
                Xbox Series X
              </a>
            </li>
            <li>
              <a href="#">
                Playstation 5
              </a>
            </li>
            <li>
              <a href="#">
                Nintendo Switch
              </a>
            </li>
            <li>
              <a href="#">
                PC
              </a>
            </li>
          </ul>
        </div>
      </nav>

      <main className={styles.main}>
        <div className={styles.container}>
          <ul className={styles.grid}>
            {games.map(({ name, image, id }) => {
              return (
                <li key={id} className={styles.card}>
                  <Link href={`/games/${id}`}>
                    <a>
                      <span className={styles.cardImage} style={{
                        backgroundImage: `url(${image.original_url})`
                      }}>
                        <span className="sr-only">{name} Cover</span>
                      </span>
                      <h2 className={styles.cardTitle}>{ name }</h2>
                      <p className={styles.cardPrice}>
                        $60.00
                      </p>
                    </a>
                  </Link>
                </li>
              )
            })}
          </ul>
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const response = await fetch(`https://www.giantbomb.com/api/games/?api_key=${process.env.GIANT_BOMB_API_KEY}&format=json&sort=original_release_date:desc&filter=original_release_date:2017-01-01%2000:00:00|2020-05-17%2000:00:00&platforms=145,146&field_list=name,image,id,name,original_release_date`);
  const { results } = await response.json();

  console.log('results', results)

  return {
    props: {
      games: results
    }
  }
}